# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AdbConnect < Formula
  desc "Connect adb to an Android phone over same-LAN Wi-Fi or Tailscale"
  homepage "https://github.com/premex-ab/adb-connect"
  version "0.1.0"
  license "Apache-2.0"

  depends_on "android-platform-tools" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/premex-ab/adb-connect/releases/download/v0.1.0/adb-connect_0.1.0_darwin_amd64.tar.gz"
      sha256 "bdfef4ec7d9125a81d3f44fa8e68bf45172c9b4779dc1188bca99f681686a451"

      define_method(:install) do
        bin.install "adb-connect"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/premex-ab/adb-connect/releases/download/v0.1.0/adb-connect_0.1.0_darwin_arm64.tar.gz"
      sha256 "0013f18fbc123ce7096bf93741f29eada88c30e1f2a51299afc2059218e5e6c0"

      define_method(:install) do
        bin.install "adb-connect"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/premex-ab/adb-connect/releases/download/v0.1.0/adb-connect_0.1.0_linux_amd64.tar.gz"
      sha256 "f63bec3986979ca6d348346499e3ce91cb79eb7443074aa9913c83f1ad8db565"
      define_method(:install) do
        bin.install "adb-connect"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/premex-ab/adb-connect/releases/download/v0.1.0/adb-connect_0.1.0_linux_arm64.tar.gz"
      sha256 "a238e8b667a910703768f425520b4bc0a30442e15bd08c1a239e930316f911d6"
      define_method(:install) do
        bin.install "adb-connect"
      end
    end
  end

  test do
    system "#{bin}/adb-connect", "version"
  end
end
