# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AdbConnect < Formula
  desc "Connect adb to an Android phone over same-LAN Wi-Fi or Tailscale"
  homepage "https://github.com/premex-ab/adb-connect"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/premex-ab/adb-connect/releases/download/v0.2.0/adb-connect_0.2.0_darwin_amd64.tar.gz"
      sha256 "9044824a0fc3b55119b4495d90ffcc930178e7215c10192203baab6b1a698e9c"

      define_method(:install) do
        bin.install "adb-connect"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/premex-ab/adb-connect/releases/download/v0.2.0/adb-connect_0.2.0_darwin_arm64.tar.gz"
      sha256 "7be35d110eeb31718ae0cb1bc9e7d2e5db87cfc10e373c1aba77c46195540bf7"

      define_method(:install) do
        bin.install "adb-connect"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/premex-ab/adb-connect/releases/download/v0.2.0/adb-connect_0.2.0_linux_amd64.tar.gz"
      sha256 "c5cb44393b720741160f7914c5c1a9c6d05edd7076e8a183afa2e911cded3b22"
      define_method(:install) do
        bin.install "adb-connect"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/premex-ab/adb-connect/releases/download/v0.2.0/adb-connect_0.2.0_linux_arm64.tar.gz"
      sha256 "a114b85ad413368362c3bb24702dfb8ecfc7dbde3a389b1c4eef88ce7da90059"
      define_method(:install) do
        bin.install "adb-connect"
      end
    end
  end

  test do
    system "#{bin}/adb-connect", "version"
  end
end
